"""empty message

Revision ID: 1d194166f97b
Revises: None
Create Date: 2015-12-14 21:36:25.709865

"""

# revision identifiers, used by Alembic.
revision = '1d194166f97b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('town_hall_level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trophy_league',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league', sa.String(length=50), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('upper', sa.Integer(), nullable=True),
    sa.Column('lower', sa.Integer(), nullable=True),
    sa.Column('fallout', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gold', sa.Integer(), nullable=True),
    sa.Column('elixir', sa.Integer(), nullable=True),
    sa.Column('de', sa.Integer(), nullable=True),
    sa.Column('found_league_id', sa.Integer(), nullable=True),
    sa.Column('found_th_id', sa.Integer(), nullable=True),
    sa.Column('th_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['found_league_id'], ['trophy_league.id'], ),
    sa.ForeignKeyConstraint(['found_th_id'], ['town_hall_level.id'], ),
    sa.ForeignKeyConstraint(['th_id'], ['town_hall_level.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('base')
    op.drop_table('trophy_league')
    op.drop_table('town_hall_level')
    ### end Alembic commands ###
